---
output: 
  bookdown::pdf_document2:
    template: KIP_head.tex
    keep_tex: true
    toc: true
    lot: true
    lof: true
bibliography: 'masterarbeit.bib'
csl: apa-6th-edition.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, concordance = TRUE)
library(summarytools)
library(kableExtra)
library(stargazer)
```

<!-- TITLE PAGE -->

\begin{titlepage}
% Titlepage (fold)
\thispagestyle{empty}%
\begin{center}
\renewcommand{\baselinestretch}{1.0}\normalsize %
\textbf{
The effect of music education on students' well-being. Empirical evidence from a field experiment}\\[1cm]
Preliminary - work in progress \\[1cm]
This draft: \today \\[1cm]
% Comments welcome \\[0.25cm]
% \renewcommand{\baselinestretch}{1.5}\normalsize
Vera Schramm \\
University of Halle-Wittenberg \\[0.75cm]
% \today
 \end{center}


\end{titlepage}

<!-- ABSTRACT -->

 \renewcommand{\baselinestretch}{1}\normalsize

 \textbf{\normalsize Abstract}
Our analyses, following the discussion above, address two central questions
using a cultural capital framework. First, who participates in music
both in and outside of school, and to what extent is such involvement
stratified by social class, race/ethnic, and gender status? Second, and relative
to the more central question discussed at the outset, do various forms of
music involvement influence academic achievement, even after accounting
for prior achievement, background statuses, and other educationally meaningful
investments? Relatedly, to what extent might disparities in music
involvement shape group-specific gaps in achievement that have been so well
documented elsewhere?

<!--  \pagenumbering{roman} -->
<!-- \setcounter{page}{2} -->

<!-- TOC -->

\clearpage
\tableofcontents

<!-- BODY -->

<!-- \pagenumbering{arabic} -->
\clearpage
\doublespacing
\pagestyle{plain}
<!-- \setcounter{page}{1} -->

<!-- INTRODUCTION -->

# Introduction
\label{sec:introduction}

In German schools, subjects like art and music are often considered less important than the typical hard subjects like math and science. Due to a lack of teachers, many classes are cancelled, of which 80\% are in the subject of music. In Saxony we see ongoing efforts to eliminate the subject of music from the curriculum entirely. Furthermore, the quality of music lessons suffers from the fact that 80\% of its teaching staff are foreign to this subject [@Moeller2017].

Music education experts are concerned about this development. According to them, music should not be regarded as a private matter. Regardless of their socioeconomic background, school children must have the opportunity to receive high level music education because it is as important for a proper education as literacy and mathematics [@Gebert2018]. Prof. Höppner, the General Secretary of the German Music Council (Generalsekretär des Deutschen Musikrats), said in an interview that music education helps to build stable self-esteem by learning to access ones own emotions [@Stoverock]. He points out that the phase where music can shape a young person explicitly well is complete by the age of 13 which stresses the importance of high quality music education for students in pre- and secondary school.

The Federal Association of Music Education (Bundesverband Musikunterricht (BMU)) has set up the "Agenda 2030" to initiate an improvement in music education. Similar to Höppner [@Stoverock], they consider music education as valuable and essential for a social and cultural society. Their position is that schools are the central place to make children gather experiences in music because all children and adolescents can be reached, regardless of their socio-economic backgrounds. It encourages children to take responsibility and to increase their sense of self-determination [@BundesverbandMusikunterricht, p. 2].

In views of this broad socieatal debate, it seems surprising that there is only little empirical research on the role of music education for childesn's outcomes. My thesis addresses this research gap and investigates the effects of music education on children's overall life satisfaction and on satisfaction in specific areas, namely satisfaction with the class, satisfaction with friends, satisfaction with music lesson and satisfaction with the situation at school. It analyzes music education in the classroom where fifth and sixth grade students have one additional hour of music education per week. The project is called "klasse.im.puls" and it promotes the establishment of musical training in secondary schools in Bavaria. The program was implemented with the intention to give every child the opportunity to learn how to play an instrument. Additional positive outcomes were expected: an increase in self-confidence and social competence, as well as a reduction in violent behavior ^[For more information:] 
My analysis focuses on the change in the overall life satisfaction and in satisfaction within specific areas reported by the students over the course of the project. The term of life satisfaction refers to a cognitive evaluation of a person's reaction to his or her life in contrast to affect, an ongoing emotional reaction. Combinden, LS and affect yield subjective well-being [@Diener2009, p. 71]. I will approach the probelm by using a multi level model, that accounts for differences on the level of the individual student, on the level of the class and on the school level. I do this by using Baysian inference...

The interest in life satisfaction as an outcome of the music project stems from the idea that higher values of LS come with many benefits. Among other positive correlates, adolescdents reporting very high levels of LS are less likely to be affected by depression, anxiety, negative affect and social stress copared to adolescents with very low life satisfaction. Also, they achieve higher SEAs and demonstrate higher mean scores of school satisfaction [@Proctor2009a, p. 928; @Gilman2006, p. 316]. These results go in line with a study by [@Suldo2004, p. 94]. The authors show that LS could be a moderating variable in predictions of the development of psychopathological behaviors. Low life satisfaction may be an indication for externalizing behavior problems in the future. When life satisfaction is on a higher level, those behavior problems are less likely to occur [@Suldo2004, p. 100] They conclude that life satisfaction might operate as a buffer against the development of subsequent externalizing behavior problems "in the face of stressful life events" [@Suldo2004. p. 101]. @Kim2003 add to the discussion that externalizing behabvior problems in turn lead to more stressful life events. That reciprocal interrelation of stressful life events and externalizing problesm(reported as delinquent behaviors) lead to a unhealthy dynamic: a viscous circle that occurs due to low life satisfaction. If higher LS leads better coping mechanisms with stressful life events, these dependencies could be reduced.
LS is also positively correlated with children having higher measures of self-esteem, internal locus of control, and extraversion [@Huebner1991, 107]. These features help in building a solid foundation for later life. On the other hand, dissatisfaction with life is associated with adolescents having poor mental or physical health and being exposed to a higher risk of considering or attempting suicide [@Valois2004, p. 94]. Furthermore, @Zullig2001 [p. 284-185] show that adolescents reporting low levels of overall life satisfaction are more likely to use drugs and alcohol earlier in life and in higher amounts than adolescents with medium or high life satisfaction. Also, anxiety and neuroticism are more common among dissatisfied than satisfied children and adolescents [@Huebner1991, 107].

Considering the statement of Höppner, one would expect the project to positively effect students' life satisfaction. Evidence for this relation would lend credibility to the project and support its continuation. It could also stress the importance of music education and signal the Ministry of Culture to keep music education in the curriculum and work on its implementation in federal states alongside Bavaria. However, there will be no indebth investigation of the analysis of any observations. Describing possible reasons for certain outcomes must be left to music and education experts...

The structure of my thesis is as follows: At first there will be an overview of the current literature. It is split into two parts: Publications about music and recent findings about measuring life satisfaction. Next, the project and the dataset will be explained. Descripitve statistics are presented alongside a detailde diagnostic on pr-treatment differences in the treatment group compared to the control goup The estimation strategy is presented in chapter four, following the results in the fifth chapter. Finally, chapter six concludes and discusses.

*Gute Einleitung bei @Southgate2009*
<!-- LITERATURE REVIEW -->
\clearpage

# Literature review
\label{sec:literature_review}

An extensive amount of reseach was done on adult life satisfaction and on methods how to measure it. From that we know that not only is life satisfaction a result of life circumstances but it determines outcomes in several areas like health, ... (see Firsch 1999 for a review (suldo and huebner, ß. 94))

Even though, the amount of research on

Life satisfaction in children and adolescents has been observed in a much lesser extent. This might be attributed to the fact that instruments for assesing children's subjective satisfaction reports have been less extensively developed. When dealing with self-reported life satisfaction in children, it is crucial that the respective child fully understands the question in order to give a valid response [@Gluskie2012; @Tomyn2016]. One must make sure that a child is old enough to know how to use a satisfaction scale. This requires abstract thinking, which children develop in early adolescent years (10-14 years) [@Gluskie2012; @Piaget1955; @Piaget1969]. @Gilman2000 habe reviwed five measurements explicitely developed to asses adolexcents' life satisfaction: The Students' Life Satisfaction Scale [@Huebner1991a], the Satisfaction With Life Scale [@Diener1985], the Perceived Life Satisfaction Scale [@Adelman1989], the Comprehensive Quality of Life Scale - School Version [@Cummins1997; @Gullone1999], and the Multodimensional Student's Life Satisfaction Scale [@Huebner1994]. The authors evaluated those measures in terms or validity and reliability and found all of the scales to be appropriate for reseach with adolescents [p. 181-188]. The demographic characteristics of the available samples show that all of the adolescents observed were older than 12 years. It remains unclear if children younger than that age are able to report valid satisfaction?.
An oher instrument was developed more recently by [@Cummins2005] which is the Personal Wellbeing Index (PWI-SC). Again, studies demonstrated reliability for this instrument as well [@Casas2011; @Casas2015; @Tomyn2011a; @Tomyn2019]. But also on those studies, all of the adolescents were at least 12 years of age, mostly even older. There is only very little evidence on the psychometric properties of the PWI-SC for children below the age of 12.
One of them is @GonzalezCarrasco2016 [p. 70] who applied the instrument for children as young as only 9 years and also found adequate fit of the data.
On the other hand, @Tomyn2016 conducted a study with children aged 10-12 and concluded that subjective wellbeing data of children must be interpreted with caution. They also show that response bias towards the extreme positive end of a scale is higher with decreasing age. The authors do not recommend using the PWI-SC for children younger than 12 years. As for the specific sample, the PWI-SC did not serve as a valid instrument for measuring the SWB.

In conclusion, measuring life satisfaction in children is more challenging than for adults and is still in progress. It is advisable to check the validity and reliability of their data when testing children.
Altogether, the children of "klasse.im.puls" might be just old enough to give valid responses when asked about their life satisfaction.

With regard to the effect of music on students' lives, most of the researchers are interested in academic outcomes and intelligence among students who are actively involved in music. Generally, there is the predominant perception of a positive link between music and cognitive abilities. @Osborne2015 (p. 14) observed improved math skills and higher subjective well-being scores in children that were part of a music project. He also found them to have a better self-control over impulsive behavior. @Yang2015 (p. 385) RELATION,@Wetter2008 (p. 372) CORRELATION , @Hille2014 (p. 62) CAUSAL EFFECTS OR CORRELATION? SECTION 6!, and @Guhn2019 (p. 316) RELATION present evidence that childrin playing music have better grades at school. But this conclusion is highly critizised. In an extiensive review  [@Schellenberg2013] of the available evidence concerning associations between music and cognitive abilities, the picture is not so clear any longer. Small associations between music training and mathematical ability in correlational and quasi-experimental studies might result from individual differences in general intellectual ability (p. 527). The available evidence simply indicates that high-functioning children (i.e., higher IQ, better performance in school) are more likely than other children to take music lessons and to perform well in mathematics and other tests of cognitive ability (p. 534). This fits with the @Hille2014 study where the oucome difference in cognitive skills between musically active and inactive children reduces greatly when holding constant observable characteristics. An other plausible interpretaion of study outcomes that fail to detect a causal relationship comes from @Wetter2008. More affluent parents can more likely afford music lessons for their child and thus, the socio-economic background may cause to higher performance at school. Despite the weakness of the above studies to draw causal inference, there is slight evidence that there may be a causal direction *from* music training *to* cognitive abilities. @Schellenberg2004 compares a two treatment groups who receive piano lesson and voice lesson respectively to a control group in which the children have drama lessons. Random assignment to the different conditions allowed for inference that music lessons caused small increases in cognitive abilities (namely larger increases in full-scale IQ). However, this does not preclude the possibility that high-functioning children are more likely driven to play music. The misconception of music being a predictor for academic achievement is also discussed by @Southgate2009 (p. 17). He comes to the point that music is rather a mediator, to some degree, of family background and student status, thus supporting arguments and theorizing partaining to cultural capulta. More recent literature provides (wortliches Zitat!). *Results from a meta-analysis, suggest that music training does not reliably enhance children and young adolescents' cognitive or academic skills, and that prvious positive findings were probably due to confounding variables, such as placebo effects and lack of random allocation of participants [@Sala2016, p. 64]. The better the design, the smaller the effect size (both methodological moderators, namely random allocation of paricipants to the treatment group and comparison to an active control group, affected the effect size...) the reliablity of the positive outcomes seems questionable. Withe respect to the mathematical oucomes, the only study comparing a music training to an active conrol goup and with random allocation of the participants to the group [@Mehr2013] found a negative effect size. These considerations uphold the conclusion that music training does not substantially enhance any non-music related cognitive skill.*

Diffuse effect
Miscnceptions arealso discussed
why those with musical training outperforming their peers in tests of intelligence or tasks often included in intelligence tests has been the focus of much research and debate.
However because of the correlational design of many of these investigations, it is difficult to establish the direction of causality unequivocally

Positive correlates are not limited to academics. [@CostaGiomi2004 CAUSAL EFFECT] show that children receiving piano lessons experience positive effects in self-esteem [@CostaGiomi2004, p. 144] but do not find an effect on math computation scores. In an other study, observing the effect of choir singing on homeless men, evidence was found that attending the choir induced positive emotional change and awareness, which was described by the participants as therapeutic [@Bailey2003, p. 23]. This was already observed by @Ruud1997 in his studeis on music and identity. He states that cultural activities, explicitly music, can "contribute to a feeling of quality of life and the subjective sense of health." (p. 96). There is one especially popular project: Venezuela's National Music Education Program "El Sistema". It is a large scale social music education program established by José Abreu in the 1970s.  300,000 children are equipped with instruments every year. They receive regular after-school lessons and are playing in orchestras. The initial goal was to prevent children from using drugs and being involved in violence and crime which was successfully achieved. Staying away from substances is one factor that indicates a more satisfied life as stated in section objective. Being in orchestras also enhanced social behavior of the students through greater concern for others and their own wellbeing. @Uy2012 [p. 13]. However positive effects go far byond keeping adolescents away from drugs and violence: El sistema teaches the participating students to "reflect and act upon the world in order to transform it" [7]. Playing in an orchestra means joy, motivation, teamwork, the aspiration to success [6]. The students pick up management and organizational skills and responsibility due to many roles and rules that they need to follow to sty in the program[p. 10]. Also, being in an orchestra gives the students the change to condeptualize themselves as part of something much larger and greater (p. 11) and they learn to express greater concern for others' and their well being (p. 13). El Sistema became internationall popular and was replicated in several countries. @Osborne2015 reviewd the outcome of El Sistema inspired projects in Australia and found improved maths skills and significantly higher subjective well-being scores in the participating group (p. 14). Students from the music program also had better self-control over impulsive behavior (p. 15) (but different patterns in different schools).  Other studies come to contrary conclusions and fail to show a significnt effect of music participation on well-being, sociel skills, emotional intelligence or self-esteem [@Schellenberg2011a, p. 190 assosiation; @Portowitz2009, p. 121] RESULTS INDICATE SIGNIFICANT DIFFERENCES BETWEEN THE GROUPS IN THE DEVELOPMENT OF THE RAGETED COGNITIVE SKILLS, EXPERIMENTAL AND CONTROL GROUP. Therefore research provides no clear picture on the relation between music and how it can effect childrens' well-being. 



Weinberg2016 BIDIRECTIONAL - INTERPRETATION WITH CAUTION

 Most of the literature on music projects look at academic outcomes. It seems like children that are actively engaged in music achieve better academic results @Yang2015 [p. 385], @Wetter2008 [p. 372], and @Hille2014 also observe better chool grades in student's that are involved in music but they bring up the concern that this might be due to READ SECTION 6

@CostaGiomi2004 describes a project in which fourth-grade public school children in Montreal received piano lessons and showed positive effects in self-esteem and music marks.
In an other study, observing the effect of choir singing on homeless men, evidence was found that attending the choir induced positive emotional change and awareness, which was described by the participants as therapeutic [@Bailey2003, p. 23]. Other effects of music lessons can be found in neuro science: @Schellenberg2004 found out that increase in IQ is significantly higher for children that receive keyboard or voice lessons compared to children who do not ^[There is increase in children's IQ regardless of their musical background which is usually a consequence of entering grade school [@Ceci1997]].

anchoring vignettes, to correct for cultural and linguistic factors.
Most of this debate has been conducted in relation to the subjective well-being
of adults. There has been relatively little discussion about its relevance to
children’s subjective well-being. Partly, this is because of a lack of large-scale
data sets containing subjective well-being ratings from a range of countries,
although there are some recent examples using subjective data from the HBSC
survey. Adamson (2007) used a single-item measure of children’s life satisfaction
(Cantril’s Ladder), as part of UNICEF Report Card 7, which compared the wellbeing
of children in 21 rich countries. More recently, Bradshaw et al. (2013)
utilised eight different subjective questions from the same survey covering
relationships, health, education and overall life satisfaction. [@Casas2015]

A central construct within the positive psychology literature is life satisfaction.
Whereas adult life satisfaction has been studied extensively, the life satisfaction of children
and adolescents has only received attention more recently. [@Proctor2009]
well-being and happiness can precede diverse positive
personal, behavioural, psychological, and social outcomes (see Lyubomirsky et al. 2005),
just as low LS and unhappiness can predict the onset of depression and psychological
disorder up to two years prior to diagnosis (see Lewinsohn et al. 1991). [@Proctor2009]

Similar findings have been reported among children and adolescents (e.g. Ash
and Huebner 2001; Casas et al. 2004; Greenspoon and Saklofske 2001; Heaven 1989;
Huebner 1991a; McKnight et al. 2002). For example, Fogle et al. (2002) found LS to be
positively correlated with extraversion and social self-efficacy, negatively correlated with
neuroticism, and

In contrast to research with adults the topic of subjective well-being and satisfaction
with life has received less attention with regard to children and adolescents (Gullone and
Cummins 1999; Huebner 1991a). It has been suggested that this situation is, at least in part,
related to the fact that instruments for assessing children’s subjective well-being and
satisfaction with life have been developed only relatively recently (see Huebner and Diener
2008; Huebner 1991b; Seligson et al. 2005). Gadermann2009

Validity... positive growth and development [@Gadermann2009, p. 230].


The takeaway from this section is we must be very careful when drawing causal conclusion and we have to adjust the methods.

This paper complements existing literature by using different music indicators and estimation strategies to provied further insight on the relationship between music and education as well as the potential souces of endogeneity.

<!-- DATA -->
\clearpage

# Data
\label{sec:data}

<!-- ESTIMATION STRATEGY -->

\clearpage

# Estimation strategy
\label{sec:estimation_strategy}

<!-- RESULTS -->
\clearpage

# Results
\label{sec:results}

As described in Section 4, estimation biases resulting from selection into treatment take place at two stages: The inital decision to take up music lessons and the decision not to give up until age 17... At such a young age, the choice of a long-term extracurricular activity such as music is strongly determined by the parents. For the parents, however, we observe a large number of characteristics, in particular theri socio-economic status, personylity, involvement with the child's edcation, and taste for the arts... [@Hille2014, p. 65]
NOTE: I have to observe parents ("parental background differences")
NOTE: Results in @Hille2014 might be driven by unobserved heterogeneity... unobserved individual characteristics coud still determine the decision to keep on playing music until age 17 rather than giving up ealier (p. 67).
NOTE: Sensitivity of @Hille2014 results to reverse causalityby performing mediation analysis in which we estimate the correlation between music practice and outcome p, while subsequently controlling for all oucomes q rather than p (p. 67). How do I address the issue of reverse causality?
Three challenges should determine the agenda of future research on this agenda.
1. separate the influence of parental and individual background from that of music (indentify a variable that increases the likelihook to learn a musical instrument without affecting the development of skills.)
2. answer the question of the extent to which extracurricular activities are substitutable (substitutes vs. compliments).
3. ong-term effects of music training on oucomes such a s labor market success or life satisfaction


<!-- CONLCUSION -->
\clearpage

# Conclusion
\label{sec:conclusion}

<!-- REFERENCES -->
\clearpage

# References {-}

\singlespacing

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
\noindent

<div id="refs"></div>


<!-- APPENDIX -->

\clearpage

# (APPENDIX) Appendix {-} 

Example of nice appendic in @Hille2014

# Figures

\clearpage

# Tables

