---
title: no pooling
author: 
  - Christoph Wunder
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    fig_caption: yes
    theme: spacelab 
    highlight: pygments
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    toc_float:
      smooth_scroll: FALSE
bibliography: literature.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment=NA)
rm(list=ls())
```
```{r, include=TRUE, message = FALSE}
library(tidyverse)
library(Hmisc)
library(mosaic)
library(foreign)
library(lme4)
library(rstanarm)
library(brms)
library(tableone)
library(RColorBrewer)
library(xtable)
library(knitr)
library(kableExtra)
library(ggdist)
library(plm)
```

```{r}
d <- readRDS("../data/d_satisfaction.RDS")
```

```{r}
d.p <- pdata.frame(d, index = c("pid", "welle"))
c1 <- plm(lsat ~  treated + welle  + tXw2 + tXw3 + tXw4 + tXw5 + 
             female + migback + hob.mus.making, data=d.p, model = "between")
summary(c1)
```
```{r}
wave2.c1 <- summary(c1)$coefficient["tXw21",1]
wave3.c1 <- summary(c1)$coefficient["tXw31",1]
wave4.c1 <- summary(c1)$coefficient["tXw41",1]
wave5.c1 <- summary(c1)$coefficient["tXw51",1]
wave2.c1.se <- summary(c1)$coefficient["tXw21",2]
wave3.c1.se <- summary(c1)$coefficient["tXw31",2]
wave4.c1.se <- summary(c1)$coefficient["tXw41",2]
wave5.c1.se <- summary(c1)$coefficient["tXw51",2]
c1.df <- data.frame(
                         wave = seq(2:5),
                         estimate = c(wave2.c1, wave3.c1, wave4.c1, wave5.c1),
                         lower = c(wave2.c1 - wave2.c1.se,
                                   wave3.c1 - wave3.c1.se,
                                   wave4.c1 - wave4.c1.se,
                                   wave5.c1 - wave5.c1.se),
                         upper = c(wave2.c1 + wave2.c1.se,
                                   wave3.c1 + wave3.c1.se,
                                   wave4.c1 + wave4.c1.se,
                                   wave5.c1 + wave5.c1.se))
c1.df
```

```{r}
complete_pool <-
  ggplot(data = c1.df, aes(x = wave, y = estimate)) +
  geom_pointrange(aes(ymin = lower, 
                      ymax = upper),
                  position=position_dodge(width=0.40)) +
  scale_x_discrete("Wave", limits=seq(2:6) )  +
  geom_hline(yintercept=0) + 
  theme(legend.position="bottom")
ggsave("../figures/complete_pool.png", complete_pool, width = 7, height = 4, units = "in")
```



```{r, results='hide'}
devtools::session_info()
```

