---
title: "Prior predictive distribution"
author: "VS"
date: "24 9 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment=NA)
rm(list=ls())
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(brms)
library(sjlabelled)
library(parallel)
library(gridExtra)
library(haven)
library(RColorBrewer)
library(ggmcmc)
library(mcmcplots)
library(bayesplot)
library(cowplot) # cowplot helps align multiple ggplots in a grid for comparison
# options(mc.cores = detectCores()) #detect number of cores for Rstan
# library(extrafont)
# windowsFonts(CMU = windowsFont("CMU Serif")) # Define CMU font as the computer modern serif font that is used in my latex template
# theme_set(theme_bw(base_family = "CMU")) # Set the gg-theme to use the latex font
# Sys.setenv(LANG="en")
library(extrafont)
library(patchwork)
theme_set(theme_bw(base_family = "Times New Roman")) # Set the gg-theme to use the latex font
if (!require("devtools")) {
  install.packages("devtools")
}
devtools::install_github("stan-dev/bayesplot")
```
```{r}
m1 <- readRDS("../results/m1.rds")
m2 <- readRDS("../results/sat_friends.rds")
m3 <- readRDS("../results/sat_class.rds")
m4 <- readRDS("../results/sat_school.rds")

post <- posterior_samples(m1)

coef <- mcmc_intervals(post[, 1:22],
               prob = .5,
               point_est = "median") +
  labs(title = "Coefficients lifes satisfaction") +
  vline_0() +
  scale_y_discrete(limits = c("b_Intercept", "b_treated1", "b_welle2", "b_welle3", "b_welle4", "b_welle5", "b_tXw21", "b_tXw31", "b_tXw41", "b_tXw51", "b_female1", "b_femaleUnknown", "b_migbackImmigrant", "b_migbackUnknown", "b_hob.mus.makingJa", "sd_pid_Intercept", "sd_school_Intercept", "sd_school_treated1", "sd_school_tXw21", "sd_school_tXw31", "sd_school_tXw41", "sd_school_tXw51"), 
  labels = c("Intercept", "Treated", "Welle 2", "Welle 3", "Welle 4", "Welle 5", "T:Welle 2", "T:Welle 3", "T:Welle 4", "T:Welle 5", "Female", "Female unknown", "Migback", "Migback unknown", "Hobby music", "PID Intercept", "School Intercept", "School treated", "School T:Welle 2", "School T:Welle 3", "T:Welle 4", "T:Welle 5")) +
  theme(axis.text.y = element_text(hjust = 0),
        axis.line.x = element_line(size = 1/4),
        axis.line.y = element_blank(),
        axis.ticks = element_blank())
ggsave("../figures/m1_coef.png", coef, width = 7, height = 5, units = "in")
coef

coef <- mcmc_intervals(post[, 1:22],
               prob = .5,
               point_est = "median") +
  labs(title = "Coefficients lifes satisfaction") +
  theme(axis.text.y = element_text(hjust = 0),
        axis.line.x = element_line(size = 1/4),
        axis.line.y = element_blank(),
        axis.ticks = element_blank())
ggsave("../figures/m1_coef.png", coef, width = 7, height = 5, units = "in")
coef

post <- posterior_samples(m2)

color_scheme_set("red")
coef <- mcmc_intervals(post[, 1:22],
               prob = .5,
               point_est = "median") +
  labs(title = "Coefficients friends") +
  theme(axis.text.y = element_text(hjust = 0),
        axis.line.x = element_line(size = 1/4),
        axis.line.y = element_blank(),
        axis.ticks = element_blank())
ggsave("../figures/friends_coef.png", coef, width = 7, height = 5, units = "in")
coef

post <- posterior_samples(m3)

color_scheme_set("red")
coef <- mcmc_intervals(post[, 1:22],
               prob = .5,
               point_est = "median") +
  labs(title = "Coefficients class") +
  theme(axis.text.y = element_text(hjust = 0),
        axis.line.x = element_line(size = 1/4),
        axis.line.y = element_blank(),
        axis.ticks = element_blank())
ggsave("../figures/class_coef.png", coef, width = 7, height = 5, units = "in")

post <- posterior_samples(m4)

color_scheme_set("red")
coef <- mcmc_intervals(post[, 1:22],
               prob = .5,
               point_est = "median") +
  labs(title = "Coefficients school") +
  theme(axis.text.y = element_text(hjust = 0),
        axis.line.x = element_line(size = 1/4),
        axis.line.y = element_blank(),
        axis.ticks = element_blank())
ggsave("../figures/school_coef.png", coef, width = 7, height = 5, units = "in")
```

