---
title: "Test"
author: "fabi"
date: "10/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

```{r, include=TRUE, message = FALSE}
library(tidyverse)
library(Hmisc)
library(mosaic)
library(foreign)
library(lme4)
library(rstanarm)
library(brms)
library(tableone)
library(RColorBrewer)
library(xtable)
library(knitr)
library(kableExtra)
library(ggdist)
library(plm)
library(broom.mixed)
```

```{r}
d <- readRDS("../data/d_sat.RDS")
welle1 <- readRDS("../data/welle1.RDS")

fit_kip_1 <- stan_glm(lsat ~ 1, data = d, refresh = -1)

fit_kip_2 <- stan_glm(lsat ~ -1 + school, data = d, refresh = -1)

fit_kip_3 <- stan_glmer(lsat ~ (1 | school), data = d, refresh = -1)

# extract country means for each model

alpha_1 <- tidyMCMC(fit_kip_1, conf.int = TRUE) %>%
  filter(term == "(Intercept)") %>%
  ## add school
  mutate(school = list(unique(as.character(d[["school"]])))) %>%
  unnest(school) %>%
  select(-term) %>%
  mutate(model = "Complete")

alpha_2 <- tidyMCMC(fit_kip_2, conf.int = TRUE) %>%
  filter(str_detect(term, "^school")) %>%
  mutate(school = str_replace(term, "^school", "")) %>%
  select(-term) %>%
  mutate(model = "No")

alphas <- as.matrix(fit_kip_3, regex_pars = "^b\\[")
alpha_mean <- as.matrix(fit_kip_3, pars = "(Intercept)")
alpha_3 <- sweep(alphas, 1, alpha_mean, FUN = "+") %>%
  as_tibble() %>%
  gather(term, value) %>%
  group_by(term) %>%
  summarise(estimate = mean(value),
            conf.low = quantile(value, 0.025),
            conf.high = quantile(value, 0.975)) %>%
  ungroup() %>%
  mutate(school = str_match(term, "school:(.*)\\]")[ , 2]) %>%
  select(-term) %>%
  mutate(model = "Partial")

all_models <-
  bind_rows(alpha_1, alpha_2, alpha_3) %>%
  # reorder school by size
  mutate(school = fct_reorder(school, estimate, mean))

compare <- ggplot(all_models, aes(x = school, y = estimate, ymin = conf.low, ymax = conf.high, color = model)) +
  geom_pointrange(position = position_dodge(width = 1)) +
  coord_flip()
ggsave("../figures/compare_models.png", compare, 
       width = 7, height = 4, units = "in")
compare



fit_kip_1 <- stan_glm(lsat ~ 1, data = welle1, refresh = -1)

fit_kip_2 <- stan_glm(lsat ~ -1 + school, data = welle1, refresh = -1)

fit_kip_3 <- stan_glmer(lsat ~ (1 | school), data = welle1, refresh = -1)

# extract country means for each model

alpha_1 <- tidyMCMC(fit_kip_1, conf.int = TRUE) %>%
  filter(term == "(Intercept)") %>%
  ## add school
  mutate(school = list(unique(as.character(d[["school"]])))) %>%
  unnest(school) %>%
  select(-term) %>%
  mutate(model = "Complete")

alpha_2 <- tidyMCMC(fit_kip_2, conf.int = TRUE) %>%
  filter(str_detect(term, "^school")) %>%
  mutate(school = str_replace(term, "^school", "")) %>%
  select(-term) %>%
  mutate(model = "No")

alphas <- as.matrix(fit_kip_3, regex_pars = "^b\\[")
alpha_mean <- as.matrix(fit_kip_3, pars = "(Intercept)")
alpha_3 <- sweep(alphas, 1, alpha_mean, FUN = "+") %>%
  as_tibble() %>%
  gather(term, value) %>%
  group_by(term) %>%
  summarise(estimate = mean(value),
            conf.low = quantile(value, 0.025),
            conf.high = quantile(value, 0.975)) %>%
  ungroup() %>%
  mutate(school = str_match(term, "school:(.*)\\]")[ , 2]) %>%
  select(-term) %>%
  mutate(model = "Partial")

all_models <-
  bind_rows(alpha_1, alpha_2, alpha_3) %>%
  # reorder school by size
  mutate(school = fct_reorder(school, estimate, mean))

compare <- ggplot(all_models, aes(x = school, y = estimate, ymin = conf.low, ymax = conf.high, color = model)) +
  geom_pointrange(position = position_dodge(width = 1)) +
  coord_flip()
ggsave <- ggsave("../figures/compare_modes.pdf", compare_models(), 
       width = 7, height = 4, units = "in")

d.p <- pdata.frame(d, index = c("pid", "welle"))

fit_kip_1 <- plm(d.p, lsat ~ 1)

fit_kip_2 <- plm(lsat ~ -1 + school)

fit_kip_3 <- stan_glmer(lsat ~ (1 | school), data = welle1, refresh = -1)

# extract country means for each model

alpha_1 <- tidyMCMC(fit_kip_1, conf.int = TRUE) %>%
  filter(term == "(Intercept)") %>%
  ## add school
  mutate(school = list(unique(as.character(d[["school"]])))) %>%
  unnest(school) %>%
  select(-term) %>%
  mutate(model = "Complete")

alpha_2 <- tidyMCMC(fit_kip_2, conf.int = TRUE) %>%
  filter(str_detect(term, "^school")) %>%
  mutate(school = str_replace(term, "^school", "")) %>%
  select(-term) %>%
  mutate(model = "No")

alphas <- as.matrix(fit_kip_3, regex_pars = "^b\\[")
alpha_mean <- as.matrix(fit_kip_3, pars = "(Intercept)")
alpha_3 <- sweep(alphas, 1, alpha_mean, FUN = "+") %>%
  as_tibble() %>%
  gather(term, value) %>%
  group_by(term) %>%
  summarise(estimate = mean(value),
            conf.low = quantile(value, 0.025),
            conf.high = quantile(value, 0.975)) %>%
  ungroup() %>%
  mutate(school = str_match(term, "school:(.*)\\]")[ , 2]) %>%
  select(-term) %>%
  mutate(model = "Partial")

all_models <-
  bind_rows(alpha_1, alpha_2, alpha_3) %>%
  # reorder school by size
  mutate(school = fct_reorder(school, estimate, mean))

compare <- ggplot(all_models, aes(x = school, y = estimate, ymin = conf.low, ymax = conf.high, color = model)) +
  geom_pointrange(position = position_dodge(width = 1)) +
  coord_flip()
ggsave <- ggsave("../figures/compare_modes.pdf", compare_models(), 
       width = 7, height = 4, units = "in")
```

